FROM registry.cn-shanghai.aliyuncs.com/doraemon_hub/ai_dev_base:ubuntu20.04-cpu-py310-transformers4.32.0-pytorch2.0.0

COPY sources.list /etc/apt/

#安装libsndfile
RUN apt-get update && apt-get install -y libsndfile1

COPY pip.conf /root/.pip/

COPY requirements.txt /tmp

RUN pip install  -r  /tmp/requirements.txt